services:
  app:
    build: .
    container_name: elab-app
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file: .env
    volumes:
      - .:/app
      - media:/app/media
      - staticfiles:/app/staticfiles
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/elab-sandbox:/var/elab-sandbox
    depends_on:
      - elab-db
      - elab-redis
    networks:
      - elab-network

  worker:
    build: .
    container_name: elab-worker
    restart: always
    command: celery -A config worker -l info
    env_file: .env
    volumes:
      - .:/app
      - media:/app/media
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/elab-sandbox:/var/elab-sandbox
    depends_on:
      - elab-db
      - elab-redis
    networks:
      - elab-network

  elab-db:
    image: postgres:15-alpine
    container_name: elab-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elab-network

  elab-redis:
    image: redis:7-alpine
    container_name: elab-redis
    restart: always
    networks:
      - elab-network

  nginx:
    image: nginx:1.27-alpine
    container_name: elab-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/var/www/static
      - media:/var/www/media
    depends_on:
      - app
    networks:
      - elab-network

volumes:
  postgres_data:
  media:
  staticfiles:

networks:
  elab-network:
    driver: bridge
