# Generated by Django 5.0.6 on 2026-06-23 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendance_manual_grading_plagiarism'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='csv_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='level_range',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='ModuleQuestionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_assignments', to='core.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module__order', 'created_at'],
                'unique_together': {('student', 'module')},
            },
        ),
        migrations.CreateModel(
            name='AssignedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_slots', to='core.question')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_questions', to='core.modulequestionassignment')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('assignment', 'order'), ('assignment', 'question')},
            },
        ),
    ]
