# Generated by Django 5.0.6 on 2026-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_csv_level_question_level_range_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulequestionassignment',
            options={'ordering': ['module__order', 'difficulty', 'created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='modulequestionassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modulequestionassignment',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='modulequestionassignment',
            unique_together={('student', 'module', 'difficulty')},
        ),
    ]
