# Generated by Django 5.0.6 on 2026-07-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_role_certificaterequest_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='proctoring_violations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
