# Generated by Django 5.0.6 on 2026-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='plagiarism_flagged',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='plagiarism_notes',
        ),
        migrations.AddField(
            model_name='submission',
            name='proctoring_logs',
            field=models.JSONField(default=list),
        ),
    ]
