# Generated by Django 5.0.6 on 2026-07-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_submission_plagiarism_flagged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_modules',
            field=models.ManyToManyField(blank=True, help_text='Modules this faculty member manages (faculty/HoD only).', related_name='managing_faculty', to='core.module'),
        ),
    ]
