# Generated by Django 5.0.6 on 2026-08-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_bio_user_managed_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(default='c_programming', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='allow_multiple_languages',
            field=models.BooleanField(default=False),
        ),
    ]
