# Generated by Django 5.0.6 on 2026-08-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_module_category_question_allow_multiple_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='starter_codes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
