# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_migrate_module_category_to_course'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.IntegerField(
                choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'),
                         (5, '5th Semester'), (6, '6th Semester'), (7, '7th Semester'), (8, '8th Semester')],
                default=1,
                help_text='Semester when this module is taught'
            ),
        ),
        migrations.RunSQL(
            """
            -- Update semester information based on existing data
            UPDATE core_module
            SET semester = 1
            WHERE name LIKE '%Basics%' OR name LIKE '%IO%' OR name LIKE '%Operators%' OR name LIKE '%Expressions%'
            OR name LIKE '%Conditionals%' OR name LIKE '%Loops%';
            
            UPDATE core_module
            SET semester = 2
            WHERE name LIKE '%Arrays%' OR name LIKE '%Strings%' OR name LIKE '%Functions%'
            OR name LIKE '%Pointers%' OR name LIKE '%Structures%' OR name LIKE '%File Handling%'
            OR name LIKE '%Advanced Concepts%';
            """
        ),
    ]