# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_module_semester'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.IntegerField(
                choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'),
                         (5, '5th Semester'), (6, '6th Semester'), (7, '7th Semester'), (8, '8th Semester')],
                default=1
            ),
        ),
    ]