# Generated by Django 5.0.6 on 2026-08-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_populate_semester_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='semester',
        ),
    ]
