# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations


def set_default_semesters(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Module = apps.get_model('core', 'Module')
    
    # Set default semester for users (1st semester for students, 1st for faculty)
    User.objects.filter(role='STUDENT').update(semester=1)
    User.objects.filter(role='FACULTY').update(semester=1)
    User.objects.filter(role='HOD').update(semester=1)
    
    # Set semesters for modules based on their names
    module_semester_mapping = {
        # First year (semester 1-2)
        'Basics': 1,
        'IO': 1,
        'Operators': 1,
        'Expressions': 1,
        'Conditionals': 2,
        'Loops': 2,
        
        # Second year (semester 3-4)
        'Arrays': 3,
        'Strings': 3,
        'Functions': 3,
        'Pointers': 4,
        'Structures': 4,
        'File Handling': 4,
        'Advanced Concepts': 4,
    }
    
    for module in Module.objects.all():
        for key, semester in module_semester_mapping.items():
            if key in module.name:
                module.semester = semester
                module.save()
                break


def reverse_func(apps, schema_editor):
    # No reverse needed for data migration
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_user_semester'),
    ]
    
    operations = [
        migrations.RunPython(set_default_semesters, reverse_func),
    ]