# Generated by Django 5.0.6 on 2026-08-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_module_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='proctoring_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Enable or disable proctoring monitoring for questions in this course.',
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='proctoring_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Enable or disable proctoring monitoring for this question.',
            ),
        ),
    ]
