# Generated by Django 5.0.6 on 2026-08-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_proctoring_enabled_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available_from_semester',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum semester a student must be in to access this course.'),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.PositiveSmallIntegerField(default=1, help_text='Academic year (1-4). Auto-updated on semester transitions.'),
        ),
    ]
