# Generated by Django 5.0.6 on 2026-08-27 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_user_year_and_course_available_from_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='semester',
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.course'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='core.course'),
        ),
    ]
